CREATE TABLE public.guard_shifts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  guard_id uuid NOT NULL,
  guard_name text NOT NULL DEFAULT 'Security Guard',
  status text NOT NULL DEFAULT 'off_duty' CHECK (status IN ('on_duty','off_duty')),
  movement_status text NOT NULL DEFAULT 'offline' CHECK (movement_status IN ('moving','stationary','offline')),
  zone_name text NOT NULL DEFAULT 'Main Patrol Zone',
  zone_center_lat double precision NOT NULL DEFAULT -26.2041,
  zone_center_lng double precision NOT NULL DEFAULT 28.0473,
  zone_radius_m integer NOT NULL DEFAULT 500 CHECK (zone_radius_m BETWEEN 50 AND 10000),
  battery_level integer CHECK (battery_level BETWEEN 0 AND 100),
  signal_strength text NOT NULL DEFAULT 'Good' CHECK (signal_strength IN ('Strong','Good','Weak','Offline')),
  started_at timestamptz,
  ended_at timestamptz,
  last_seen_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE ON public.guard_shifts TO authenticated;
GRANT ALL ON public.guard_shifts TO service_role;
ALTER TABLE public.guard_shifts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "guards create own shifts" ON public.guard_shifts FOR INSERT TO authenticated WITH CHECK (guard_id = auth.uid());
CREATE POLICY "guards view own or company operators view all" ON public.guard_shifts FOR SELECT TO authenticated USING (guard_id = auth.uid() OR public.has_role(auth.uid(), 'security_company'));
CREATE POLICY "guards update own or company operators control" ON public.guard_shifts FOR UPDATE TO authenticated USING (guard_id = auth.uid() OR public.has_role(auth.uid(), 'security_company')) WITH CHECK (guard_id = auth.uid() OR public.has_role(auth.uid(), 'security_company'));

CREATE TABLE public.guard_locations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shift_id uuid NOT NULL REFERENCES public.guard_shifts(id) ON DELETE CASCADE,
  guard_id uuid NOT NULL,
  latitude double precision NOT NULL CHECK (latitude BETWEEN -90 AND 90),
  longitude double precision NOT NULL CHECK (longitude BETWEEN -180 AND 180),
  accuracy double precision,
  speed double precision,
  heading double precision,
  battery_level integer CHECK (battery_level BETWEEN 0 AND 100),
  signal_strength text NOT NULL DEFAULT 'Good' CHECK (signal_strength IN ('Strong','Good','Weak','Offline')),
  device_timestamp timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT ON public.guard_locations TO authenticated;
GRANT ALL ON public.guard_locations TO service_role;
ALTER TABLE public.guard_locations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "guards stream own locations" ON public.guard_locations FOR INSERT TO authenticated WITH CHECK (guard_id = auth.uid() AND EXISTS (SELECT 1 FROM public.guard_shifts s WHERE s.id = shift_id AND s.guard_id = auth.uid() AND s.status = 'on_duty'));
CREATE POLICY "guards view own or company operators view all locations" ON public.guard_locations FOR SELECT TO authenticated USING (guard_id = auth.uid() OR public.has_role(auth.uid(), 'security_company'));

CREATE INDEX guard_shifts_active_idx ON public.guard_shifts (status, last_seen_at DESC);
CREATE INDEX guard_locations_shift_time_idx ON public.guard_locations (shift_id, device_timestamp DESC);

CREATE OR REPLACE FUNCTION public.touch_guard_shift()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  NEW.updated_at = now();
  IF NEW.status = 'off_duty' THEN
    NEW.movement_status = 'offline';
    NEW.signal_strength = 'Offline';
    NEW.ended_at = COALESCE(NEW.ended_at, now());
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER trg_touch_guard_shift BEFORE UPDATE ON public.guard_shifts FOR EACH ROW EXECUTE FUNCTION public.touch_guard_shift();

CREATE OR REPLACE FUNCTION public.request_role(_role public.app_role)
RETURNS public.role_status
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE s public.role_status;
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Not signed in'; END IF;
  s := CASE WHEN _role IN ('civilian','guardian','family_member','employee') THEN 'approved' ELSE 'pending' END;
  INSERT INTO public.user_roles(user_id, role, status) VALUES (auth.uid(), _role, s)
  ON CONFLICT (user_id, role) DO UPDATE SET status = CASE WHEN public.user_roles.status='rejected' THEN s ELSE public.user_roles.status END;
  INSERT INTO public.audit_logs(actor_id,action,details) VALUES (auth.uid(),'role_requested',jsonb_build_object('role',_role,'status',s));
  RETURN s;
END;
$$;

ALTER PUBLICATION supabase_realtime ADD TABLE public.guard_shifts;
ALTER PUBLICATION supabase_realtime ADD TABLE public.guard_locations;